# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.SmallIntegerField(unique=True)),
                ('name', models.TimeField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dish', models.SmallIntegerField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vendor', models.SmallIntegerField(unique=True)),
                ('name', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='id_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendors'),
        ),
    ]
