# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180327_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
