# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180327_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
