# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180327_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('Сегодня', 'Today'), ('Завтра', 'Tomorrow')], default='Сегодня', max_length=10),
        ),
    ]
